Added button to view alerts
siglens/siglens pull request #195
Opened 2023-12-07 07:14 UTC by PratikshaPatil77

# Description
I have been added a button to view alerts associated with contact point while deleting contact point.

Fixes #104

# Testing
I was test this code by creating contact points and alerts that are associated with contact point and when I try to delete that particular contact point it raise delete popup where it shows the button to view alerts associated with that contact point and when we click the button it shows dropdown list of alerts which are associated with that contact point.

# Checklist:
Before marking your pull request as ready for review, complete the following.

- [ x ] I have self-reviewed this PR.
- [ x ] I have removed all print-debugging and commented-out code that should not be merged.
- [ x ] I have added sufficient comments in my code, particularly in hard-to-understand areas.
- [ ] I have formatted the code, if applicable. For Go, I have run `goimports -w .`.

2023-12-08 10:52 UTC, sonamgupta21 requested changes
Noticed functions `showDeleteContactDialog` and `getAllAlertsWithSameContactPoint` are written twice. 

Could you please remove one of them?

2023-12-08 11:20 UTC, sonamgupta21 commented
Change the button text from 'View alerts associated with this contact point' to 'View associated Alerts.' 
Also, convert it into a dropdown format so that when the user clicks, a list of alerts is displayed. 
You can refer to other dropdowns for the CSS style.

2023-12-12 17:00 UTC, PratikshaPatil77 commented
Hi, @sonamgupta21
I've made the changes and it is ready to review.
Thank you.

2023-12-14 04:56 UTC, sonamgupta21 approved these changes

2023-12-14 10:27 UTC, merged