while adding panel it takes to edit panel page
siglens/siglens pull request #466
Opened 2024-02-05 09:47 UTC by PratikshaPatil77

# Description
When you add a dashboard panel, it takes you to the page to edit that panel. Once you click the + Add Panel button, it make the panel and immediately take you to the page where you can edit that panel.

Fixes #443 

# Checklist:
Before marking your pull request as ready for review, complete the following.

- [ x ] I have self-reviewed this PR.
- [ x ] I have removed all print-debugging and commented-out code that should not be merged.
- [ x ] I have added sufficient comments in my code, particularly in hard-to-understand areas.
- [ ] I have formatted the code, if applicable. For Go, I have run `goimports -w .`.

2024-02-05 17:40 UTC, AndrewHess reviewed
When I add a panel, add a query, select the Data Source, select a chart type and click Apply, I don't see the new panel on the dashboard. Is this working for you?

2024-02-06 04:47 UTC, PratikshaPatil77 commented
> When I add a panel, add a query, select the Data Source, select a chart type and click Apply, I don't see the new panel on the dashboard. Is this working for you?

I apologize . Initially, I only verified the redirection to the edit panel page after clicking "Add Panel."
I overlooked confirming the panel's successful saving. Checking it now.

2024-02-06 04:48 UTC, PratikshaPatil77 commented
Changes will be ready soon.

2024-02-08 15:57 UTC, PratikshaPatil77 commented
@AndrewHess  @nbhavana @sonamgupta21 
Changes are ready for review.
 Please have a look and if any changes required please let me know.

2024-02-08 16:20 UTC, AndrewHess reviewed
Looks pretty good to me, just a minor comment about indentation

2024-02-08 16:20 UTC, AndrewHess commented on static/js/dashboard.js
> +        $('.panelDisplay #empty-response').hide();
nit: it looks like this is indented one indent too far, right?

2024-02-08 18:09 UTC, sonamgupta21 requested changes
There's one issue: When we duplicate a panel, it opens the edit panel screen, which shouldn't happen.

2024-02-09 15:15 UTC, sonamgupta21 approved these changes

2024-02-09 15:27 UTC, merged